const originData = [
  {
    name: 'Harry Potter',
    species: 'human',
    gender: 'male',
    house: 'Gryffindor',
    dateOfBirth: '31-07-1980',
    yearOfBirth: 1980,
    ancestry: 'half-blood',
    eyeColour: 'green',
    hairColour: 'black',
    wand: {
      wood: 'holly',
      core: 'phoenix feather',
      length: 11
    },
    patronus: 'stag',
    hogwartsStudent: true,
    hogwartsStaff: false,
    actor: 'Daniel Radcliffe',
    alive: true,
    image: 'http://hp-api.herokuapp.com/images/harry.jpg'
  },
  {
    name: 'Luna Lovegood',
    species: 'human',
    gender: 'female',
    house: 'Ravenclaw',
    dateOfBirth: '13-02-1981',
    yearOfBirth: 1981,
    ancestry: '',
    eyeColour: 'grey',
    hairColour: 'blonde',
    wand: {
      wood: '',
      core: '',
      length: ''
    },
    patronus: 'hare',
    hogwartsStudent: true,
    hogwartsStaff: false,
    actor: 'Evanna Lynch',
    alive: true,
    image: 'http://hp-api.herokuapp.com/images/luna.jpg'
  },
  {
    name: 'Cedric Diggory',
    species: 'human',
    gender: 'male',
    house: 'Hufflepuff',
    dateOfBirth: '',
    yearOfBirth: 1977,
    ancestry: '',
    eyeColour: 'grey',
    hairColour: 'brown',
    wand: {
      wood: 'ash',
      core: 'unicorn hair',
      length: 12.25
    },
    patronus: '',
    hogwartsStudent: true,
    hogwartsStaff: false,
    actor: 'Robert Pattinson',
    alive: false,
    image: 'http://hp-api.herokuapp.com/images/cedric.png'
  },
  {
    name: 'Bellatrix Lestrange',
    species: 'human',
    gender: 'female',
    house: 'Slytherin',
    dateOfBirth: '',
    yearOfBirth: 1951,
    ancestry: 'pure-blood',
    eyeColour: 'brown',
    hairColour: 'black',
    wand: {
      wood: 'walnut',
      core: 'dragon heartstring',
      length: 12.75
    },
    patronus: '',
    hogwartsStudent: false,
    hogwartsStaff: false,
    actor: 'Helena Bonham Carter',
    alive: false,
    image: 'http://hp-api.herokuapp.com/images/bellatrix.jpg'
  },
  {
    name: 'Argus Filch',
    species: 'human',
    gender: 'male',
    house: '',
    dateOfBirth: '',
    yearOfBirth: '',
    ancestry: 'squib',
    eyeColour: '',
    hairColour: 'grey',
    wand: {
      wood: '',
      core: '',
      length: ''
    },
    patronus: '',
    hogwartsStudent: false,
    hogwartsStaff: true,
    actor: 'David Bradley',
    alive: true,
    image: 'http://hp-api.herokuapp.com/images/filch.jpg'
  }
];
const dataModificada = [
  {
    name: 'Harry Potter',
    species: 'human',
    gender: 'male',
    house: 'Gryffindor',
    dateOfBirth: '31-07-1980',
    yearOfBirth: 1980,
    ancestry: 'half-blood',
    eyeColour: 'green',
    hairColour: 'black',
    wand: { wood: 'holly', core: 'phoenix feather', length: 11 },
    patronus: 'stag',
    hogwartsStudent: true,
    hogwartsStaff: false,
    actor: 'Daniel Radcliffe',
    alive: true,
    image: 'http://hp-api.herokuapp.com/images/harry.jpg',
    age: 39,
    role: 'Estudiante',
    insignia:
      'https://http2.mlstatic.com/insignia-gryffindor-harry-potter-D_NQ_NP_651875-MLC29350802141_022019-F.jpg'
  },
  {
    name: 'Luna Lovegood',
    species: 'human',
    gender: 'female',
    house: 'Ravenclaw',
    dateOfBirth: '13-02-1981',
    yearOfBirth: 1981,
    ancestry: '',
    eyeColour: 'grey',
    hairColour: 'blonde',
    wand: { wood: '', core: '', length: '' },
    patronus: 'hare',
    hogwartsStudent: true,
    hogwartsStaff: false,
    actor: 'Evanna Lynch',
    alive: true,
    image: 'http://hp-api.herokuapp.com/images/luna.jpg',
    age: 38,
    role: 'Estudiante',
    insignia: 'https://cdn.wallpapersafari.com/72/0/zoDO7R.jpg'
  },
  {
    name: 'Cedric Diggory',
    species: 'human',
    gender: 'male',
    house: 'Hufflepuff',
    dateOfBirth: '',
    yearOfBirth: 1977,
    ancestry: '',
    eyeColour: 'grey',
    hairColour: 'brown',
    wand: { wood: 'ash', core: 'unicorn hair', length: 12.25 },
    patronus: '',
    hogwartsStudent: true,
    hogwartsStaff: false,
    actor: 'Robert Pattinson',
    alive: false,
    image: 'http://hp-api.herokuapp.com/images/cedric.png',
    age: 42,
    role: 'Estudiante',
    insignia:
      'https://images-na.ssl-images-amazon.com/images/I/61CZcW%2ByIDL._SY606_.jpg'
  },
  {
    name: 'Bellatrix Lestrange',
    species: 'human',
    gender: 'female',
    house: 'Slytherin',
    dateOfBirth: '',
    yearOfBirth: 1951,
    ancestry: 'pure-blood',
    eyeColour: 'brown',
    hairColour: 'black',
    wand: { wood: 'walnut', core: 'dragon heartstring', length: 12.75 },
    patronus: '',
    hogwartsStudent: false,
    hogwartsStaff: false,
    actor: 'Helena Bonham Carter',
    alive: false,
    image: 'http://hp-api.herokuapp.com/images/bellatrix.jpg',
    age: 68,
    role: '',
    insignia:
      'https://cdn.shopify.com/s/files/1/2393/5817/products/Harry-Potter-Slytherin-Crest-Kids-T-Shirt-Logo-Web_1400x.jpg?v=1511172841'
  },
  {
    name: 'Argus Filch',
    species: 'human',
    gender: 'male',
    house: '',
    dateOfBirth: '',
    yearOfBirth: '',
    ancestry: 'squib',
    eyeColour: '',
    hairColour: 'grey',
    wand: { wood: '', core: '', length: '' },
    patronus: '',
    hogwartsStudent: false,
    hogwartsStaff: true,
    actor: 'David Bradley',
    alive: true,
    image: 'http://hp-api.herokuapp.com/images/filch.jpg',
    age: 0,
    role: 'Maestro',
    insignia:
      'https://pngimage.net/wp-content/uploads/2018/06/rayo-harry-potter-png-.png'
  }
];

const dataOrdenada = [
  {
    name: 'Argus Filch',
    species: 'human',
    gender: 'male',
    house: '',
    dateOfBirth: '',
    yearOfBirth: '',
    ancestry: 'squib',
    eyeColour: '',
    hairColour: 'grey',
    wand: { wood: '', core: '', length: '' },
    patronus: '',
    hogwartsStudent: false,
    hogwartsStaff: true,
    actor: 'David Bradley',
    alive: true,
    image: 'http://hp-api.herokuapp.com/images/filch.jpg',
    age: 0,
    role: 'Maestro',
    insignia:
      'https://pngimage.net/wp-content/uploads/2018/06/rayo-harry-potter-png-.png'
  },
  {
    name: 'Luna Lovegood',
    species: 'human',
    gender: 'female',
    house: 'Ravenclaw',
    dateOfBirth: '13-02-1981',
    yearOfBirth: 1981,
    ancestry: '',
    eyeColour: 'grey',
    hairColour: 'blonde',
    wand: { wood: '', core: '', length: '' },
    patronus: 'hare',
    hogwartsStudent: true,
    hogwartsStaff: false,
    actor: 'Evanna Lynch',
    alive: true,
    image: 'http://hp-api.herokuapp.com/images/luna.jpg',
    age: 38,
    role: 'Estudiante',
    insignia: 'https://cdn.wallpapersafari.com/72/0/zoDO7R.jpg'
  },
  {
    name: 'Harry Potter',
    species: 'human',
    gender: 'male',
    house: 'Gryffindor',
    dateOfBirth: '31-07-1980',
    yearOfBirth: 1980,
    ancestry: 'half-blood',
    eyeColour: 'green',
    hairColour: 'black',
    wand: { wood: 'holly', core: 'phoenix feather', length: 11 },
    patronus: 'stag',
    hogwartsStudent: true,
    hogwartsStaff: false,
    actor: 'Daniel Radcliffe',
    alive: true,
    image: 'http://hp-api.herokuapp.com/images/harry.jpg',
    age: 39,
    role: 'Estudiante',
    insignia:
      'https://http2.mlstatic.com/insignia-gryffindor-harry-potter-D_NQ_NP_651875-MLC29350802141_022019-F.jpg'
  },
  {
    name: 'Cedric Diggory',
    species: 'human',
    gender: 'male',
    house: 'Hufflepuff',
    dateOfBirth: '',
    yearOfBirth: 1977,
    ancestry: '',
    eyeColour: 'grey',
    hairColour: 'brown',
    wand: { wood: 'ash', core: 'unicorn hair', length: 12.25 },
    patronus: '',
    hogwartsStudent: true,
    hogwartsStaff: false,
    actor: 'Robert Pattinson',
    alive: false,
    image: 'http://hp-api.herokuapp.com/images/cedric.png',
    age: 42,
    role: 'Estudiante',
    insignia:
      'https://images-na.ssl-images-amazon.com/images/I/61CZcW%2ByIDL._SY606_.jpg'
  },
  {
    name: 'Bellatrix Lestrange',
    species: 'human',
    gender: 'female',
    house: 'Slytherin',
    dateOfBirth: '',
    yearOfBirth: 1951,
    ancestry: 'pure-blood',
    eyeColour: 'brown',
    hairColour: 'black',
    wand: { wood: 'walnut', core: 'dragon heartstring', length: 12.75 },
    patronus: '',
    hogwartsStudent: false,
    hogwartsStaff: false,
    actor: 'Helena Bonham Carter',
    alive: false,
    image: 'http://hp-api.herokuapp.com/images/bellatrix.jpg',
    age: 68,
    role: '',
    insignia:
      'https://cdn.shopify.com/s/files/1/2393/5817/products/Harry-Potter-Slytherin-Crest-Kids-T-Shirt-Logo-Web_1400x.jpg?v=1511172841'
  }
];
const dataOrdenadaDescendente = [
  {
    name: 'Bellatrix Lestrange',
    species: 'human',
    gender: 'female',
    house: 'Slytherin',
    dateOfBirth: '',
    yearOfBirth: 1951,
    ancestry: 'pure-blood',
    eyeColour: 'brown',
    hairColour: 'black',
    wand: { wood: 'walnut', core: 'dragon heartstring', length: 12.75 },
    patronus: '',
    hogwartsStudent: false,
    hogwartsStaff: false,
    actor: 'Helena Bonham Carter',
    alive: false,
    image: 'http://hp-api.herokuapp.com/images/bellatrix.jpg',
    age: 68,
    role: '',
    insignia:
      'https://cdn.shopify.com/s/files/1/2393/5817/products/Harry-Potter-Slytherin-Crest-Kids-T-Shirt-Logo-Web_1400x.jpg?v=1511172841'
  },
  {
    name: 'Cedric Diggory',
    species: 'human',
    gender: 'male',
    house: 'Hufflepuff',
    dateOfBirth: '',
    yearOfBirth: 1977,
    ancestry: '',
    eyeColour: 'grey',
    hairColour: 'brown',
    wand: { wood: 'ash', core: 'unicorn hair', length: 12.25 },
    patronus: '',
    hogwartsStudent: true,
    hogwartsStaff: false,
    actor: 'Robert Pattinson',
    alive: false,
    image: 'http://hp-api.herokuapp.com/images/cedric.png',
    age: 42,
    role: 'Estudiante',
    insignia:
      'https://images-na.ssl-images-amazon.com/images/I/61CZcW%2ByIDL._SY606_.jpg'
  },
  {
    name: 'Harry Potter',
    species: 'human',
    gender: 'male',
    house: 'Gryffindor',
    dateOfBirth: '31-07-1980',
    yearOfBirth: 1980,
    ancestry: 'half-blood',
    eyeColour: 'green',
    hairColour: 'black',
    wand: { wood: 'holly', core: 'phoenix feather', length: 11 },
    patronus: 'stag',
    hogwartsStudent: true,
    hogwartsStaff: false,
    actor: 'Daniel Radcliffe',
    alive: true,
    image: 'http://hp-api.herokuapp.com/images/harry.jpg',
    age: 39,
    role: 'Estudiante',
    insignia:
      'https://http2.mlstatic.com/insignia-gryffindor-harry-potter-D_NQ_NP_651875-MLC29350802141_022019-F.jpg'
  },
  {
    name: 'Luna Lovegood',
    species: 'human',
    gender: 'female',
    house: 'Ravenclaw',
    dateOfBirth: '13-02-1981',
    yearOfBirth: 1981,
    ancestry: '',
    eyeColour: 'grey',
    hairColour: 'blonde',
    wand: { wood: '', core: '', length: '' },
    patronus: 'hare',
    hogwartsStudent: true,
    hogwartsStaff: false,
    actor: 'Evanna Lynch',
    alive: true,
    image: 'http://hp-api.herokuapp.com/images/luna.jpg',
    age: 38,
    role: 'Estudiante',
    insignia: 'https://cdn.wallpapersafari.com/72/0/zoDO7R.jpg'
  },
  {
    name: 'Argus Filch',
    species: 'human',
    gender: 'male',
    house: '',
    dateOfBirth: '',
    yearOfBirth: '',
    ancestry: 'squib',
    eyeColour: '',
    hairColour: 'grey',
    wand: { wood: '', core: '', length: '' },
    patronus: '',
    hogwartsStudent: false,
    hogwartsStaff: true,
    actor: 'David Bradley',
    alive: true,
    image: 'http://hp-api.herokuapp.com/images/filch.jpg',
    age: 0,
    role: 'Maestro',
    insignia:
      'https://pngimage.net/wp-content/uploads/2018/06/rayo-harry-potter-png-.png'
  }
];
const filterGeneroF = [
  {
    name: 'Luna Lovegood',
    species: 'human',
    gender: 'female',
    house: 'Ravenclaw',
    dateOfBirth: '13-02-1981',
    yearOfBirth: 1981,
    ancestry: '',
    eyeColour: 'grey',
    hairColour: 'blonde',
    wand: { wood: '', core: '', length: '' },
    patronus: 'hare',
    hogwartsStudent: true,
    hogwartsStaff: false,
    actor: 'Evanna Lynch',
    alive: true,
    image: 'http://hp-api.herokuapp.com/images/luna.jpg',
    age: 38,
    role: 'Estudiante',
    insignia: 'https://cdn.wallpapersafari.com/72/0/zoDO7R.jpg'
  },
  {
    name: 'Bellatrix Lestrange',
    species: 'human',
    gender: 'female',
    house: 'Slytherin',
    dateOfBirth: '',
    yearOfBirth: 1951,
    ancestry: 'pure-blood',
    eyeColour: 'brown',
    hairColour: 'black',
    wand: { wood: 'walnut', core: 'dragon heartstring', length: 12.75 },
    patronus: '',
    hogwartsStudent: false,
    hogwartsStaff: false,
    actor: 'Helena Bonham Carter',
    alive: false,
    image: 'http://hp-api.herokuapp.com/images/bellatrix.jpg',
    age: 68,
    role: '',
    insignia:
      'https://cdn.shopify.com/s/files/1/2393/5817/products/Harry-Potter-Slytherin-Crest-Kids-T-Shirt-Logo-Web_1400x.jpg?v=1511172841'
  }
];
const filterGeneroM = [
  {
    name: 'Harry Potter',
    species: 'human',
    gender: 'male',
    house: 'Gryffindor',
    dateOfBirth: '31-07-1980',
    yearOfBirth: 1980,
    ancestry: 'half-blood',
    eyeColour: 'green',
    hairColour: 'black',
    wand: { wood: 'holly', core: 'phoenix feather', length: 11 },
    patronus: 'stag',
    hogwartsStudent: true,
    hogwartsStaff: false,
    actor: 'Daniel Radcliffe',
    alive: true,
    image: 'http://hp-api.herokuapp.com/images/harry.jpg',
    age: 39,
    role: 'Estudiante',
    insignia:
      'https://http2.mlstatic.com/insignia-gryffindor-harry-potter-D_NQ_NP_651875-MLC29350802141_022019-F.jpg'
  },
  {
    name: 'Cedric Diggory',
    species: 'human',
    gender: 'male',
    house: 'Hufflepuff',
    dateOfBirth: '',
    yearOfBirth: 1977,
    ancestry: '',
    eyeColour: 'grey',
    hairColour: 'brown',
    wand: { wood: 'ash', core: 'unicorn hair', length: 12.25 },
    patronus: '',
    hogwartsStudent: true,
    hogwartsStaff: false,
    actor: 'Robert Pattinson',
    alive: false,
    image: 'http://hp-api.herokuapp.com/images/cedric.png',
    age: 42,
    role: 'Estudiante',
    insignia:
      'https://images-na.ssl-images-amazon.com/images/I/61CZcW%2ByIDL._SY606_.jpg'
  },
  {
    name: 'Argus Filch',
    species: 'human',
    gender: 'male',
    house: '',
    dateOfBirth: '',
    yearOfBirth: '',
    ancestry: 'squib',
    eyeColour: '',
    hairColour: 'grey',
    wand: { wood: '', core: '', length: '' },
    patronus: '',
    hogwartsStudent: false,
    hogwartsStaff: true,
    actor: 'David Bradley',
    alive: true,
    image: 'http://hp-api.herokuapp.com/images/filch.jpg',
    age: 0,
    role: 'Maestro',
    insignia:
      'https://pngimage.net/wp-content/uploads/2018/06/rayo-harry-potter-png-.png'
  }
];

const sortIgual = [
  {
    name: 'Harry Potter',
    species: 'human',
    gender: 'male',
    house: 'Gryffindor',
    dateOfBirth: '31-07-1980',
    yearOfBirth: 1980,
    ancestry: 'half-blood',
    eyeColour: 'green',
    hairColour: 'black',
    wand: { wood: 'holly', core: 'phoenix feather', length: 11 },
    patronus: 'stag',
    hogwartsStudent: true,
    hogwartsStaff: false,
    actor: 'Daniel Radcliffe',
    alive: true,
    image: 'http://hp-api.herokuapp.com/images/harry.jpg',
    age: 39,
    role: 'Estudiante',
    insignia:
      'https://http2.mlstatic.com/insignia-gryffindor-harry-potter-D_NQ_NP_651875-MLC29350802141_022019-F.jpg'
  }, {
    name: 'Ron Weasley',
    species: 'human',
    gender: 'male',
    house: 'Gryffindor',
    dateOfBirth: '01-03-1980',
    yearOfBirth: 1980,
    ancestry: 'pure-blood',
    eyeColour: 'blue',
    hairColour: 'red',
    wand: { wood: 'willow', 
      core: 'unicorn tail-hair', 
      length: 14 },
    patronus: 'Jack Russell terrier',
    hogwartsStudent: true,
    hogwartsStaff: false,
    actor: 'Rupert Grint',
    alive: true,
    image: 'http://hp-api.herokuapp.com/images/ron.jpg',
    age: 39,
    role: 'Estudiante',
    insignia:
      'https://http2.mlstatic.com/insignia-gryffindor-harry-potter-D_NQ_NP_651875-MLC29350802141_022019-F.jpg'
  }
];

window.GlobalFunctions.dataModificada = dataModificada;
window.GlobalFunctions.originData = originData;
window.GlobalFunctions.dataOrdenada = dataOrdenada;
window.GlobalFunctions.dataOrdenadaDescendente = dataOrdenadaDescendente;
window.GlobalFunctions.filterGeneroF = filterGeneroF;
window.GlobalFunctions.filterGeneroM = filterGeneroM;
window.GlobalFunctions.sortIgual = sortIgual;